# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AYR1EKQsAT6bp6Qy7mGwUQjIfAgtMNiA
"""

class Node:
    def __init__(self, data):
        self.next = None
        self.data = data

class LinkedList:
    def __init__(self):
        self.head = None

    def append(self, data):
        new_node = Node(data)
        if self.head is None:
            self.head = new_node
        else:
            current = self.head
            while current.next is not None:
                current = current.next
            current.next = new_node

    def display(self):
        current = self.head
        while current is not None:
            print('Conteúdo:', current.data)
            print('------------------------')
            current = current.next

    def remover_duplicatas(self):
        if self.head is None:
          print("A lista está vazia")

        visto = set()
        current = self.head
        anterior = None

        while current is not None:
            if current.data in visto:
                anterior.next = current.next
            else:
                visto.add(current.data)
                anterior = current
            current = current.next



lista = LinkedList()
lista.append(1)
lista.append(2)
lista.append(3)
lista.append(2)
lista.append(4)
lista.append(1)

print("Lista original:")
lista.display()

lista.remover_duplicatas()

print("\nLista após remoção de duplicatas:")
lista.display()